name: Generate Snake

on:
  schedule: # Runs at 23:50 UTC every day
    - cron: "50 23 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: ifconfigbrian
          outputs: dist/snake.svg
      - name: Push Snake to the output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
